// Generated by gencpp from file beginner_tutorials/mensajeTest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MENSAJETEST_H
#define BEGINNER_TUTORIALS_MESSAGE_MENSAJETEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct mensajeTest_
{
  typedef mensajeTest_<ContainerAllocator> Type;

  mensajeTest_()
    : numero(0)  {
    }
  mensajeTest_(const ContainerAllocator& _alloc)
    : numero(0)  {
  (void)_alloc;
    }



   typedef uint32_t _numero_type;
  _numero_type numero;





  typedef boost::shared_ptr< ::beginner_tutorials::mensajeTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::mensajeTest_<ContainerAllocator> const> ConstPtr;

}; // struct mensajeTest_

typedef ::beginner_tutorials::mensajeTest_<std::allocator<void> > mensajeTest;

typedef boost::shared_ptr< ::beginner_tutorials::mensajeTest > mensajeTestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::mensajeTest const> mensajeTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::mensajeTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/luis/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::mensajeTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::mensajeTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::mensajeTest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b32de927a501baab19ed61de1e6e9fe3";
  }

  static const char* value(const ::beginner_tutorials::mensajeTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb32de927a501baabULL;
  static const uint64_t static_value2 = 0x19ed61de1e6e9fe3ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/mensajeTest";
  }

  static const char* value(const ::beginner_tutorials::mensajeTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 numero\n\
";
  }

  static const char* value(const ::beginner_tutorials::mensajeTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numero);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mensajeTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::mensajeTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::mensajeTest_<ContainerAllocator>& v)
  {
    s << indent << "numero: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.numero);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MENSAJETEST_H
