// Generated by gencpp from file beginner_tutorials/tipo_servicioResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TIPO_SERVICIORESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_TIPO_SERVICIORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct tipo_servicioResponse_
{
  typedef tipo_servicioResponse_<ContainerAllocator> Type;

  tipo_servicioResponse_()
    : resultado1(0)  {
    }
  tipo_servicioResponse_(const ContainerAllocator& _alloc)
    : resultado1(0)  {
  (void)_alloc;
    }



   typedef int64_t _resultado1_type;
  _resultado1_type resultado1;





  typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> const> ConstPtr;

}; // struct tipo_servicioResponse_

typedef ::beginner_tutorials::tipo_servicioResponse_<std::allocator<void> > tipo_servicioResponse;

typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioResponse > tipo_servicioResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioResponse const> tipo_servicioResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/luis/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6a431a936da90ccdc31e14067c50778";
  }

  static const char* value(const ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6a431a936da90ccULL;
  static const uint64_t static_value2 = 0xdc31e14067c50778ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/tipo_servicioResponse";
  }

  static const char* value(const ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 resultado1\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resultado1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tipo_servicioResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::tipo_servicioResponse_<ContainerAllocator>& v)
  {
    s << indent << "resultado1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.resultado1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TIPO_SERVICIORESPONSE_H
