// Generated by gencpp from file beginner_tutorials/tipo_servicioRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TIPO_SERVICIOREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_TIPO_SERVICIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct tipo_servicioRequest_
{
  typedef tipo_servicioRequest_<ContainerAllocator> Type;

  tipo_servicioRequest_()
    : argumento1(0)  {
    }
  tipo_servicioRequest_(const ContainerAllocator& _alloc)
    : argumento1(0)  {
  (void)_alloc;
    }



   typedef int64_t _argumento1_type;
  _argumento1_type argumento1;





  typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct tipo_servicioRequest_

typedef ::beginner_tutorials::tipo_servicioRequest_<std::allocator<void> > tipo_servicioRequest;

typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioRequest > tipo_servicioRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::tipo_servicioRequest const> tipo_servicioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/luis/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc233777ccbd400a29154e5bfdd57036";
  }

  static const char* value(const ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc233777ccbd400aULL;
  static const uint64_t static_value2 = 0x29154e5bfdd57036ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/tipo_servicioRequest";
  }

  static const char* value(const ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 argumento1\n\
";
  }

  static const char* value(const ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.argumento1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tipo_servicioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::tipo_servicioRequest_<ContainerAllocator>& v)
  {
    s << indent << "argumento1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.argumento1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TIPO_SERVICIOREQUEST_H
